adapt container to connect by default to the recomended NordVpn server

diff --git a/Dockerfile.armhf b/Dockerfile.armhf
--- a/Dockerfile.armhf
+++ b/Dockerfile.armhf
@@ -1,20 +1,22 @@
-FROM resin/armhf-alpine
-MAINTAINER David Personette <dperson@gmail.com>
+FROM resin/armhf-alpine:3.7
 
-# Install openvpn
+LABEL maintainer="Julio Gutierrez <bubuntux@gmail.com>"
+
+COPY nordVpn.sh /usr/bin
+CMD nordVpn.sh
+
+HEALTHCHECK --start-period=5s --timeout=15s --interval=60s \
+			CMD curl -fL 'https://api.ipify.org' || exit 1
+
 RUN ["cross-build-start"]
+	# Install dependencies 
 RUN apk --no-cache --no-progress upgrade && \
-    apk --no-cache --no-progress add bash curl ip6tables iptables openvpn \
-                shadow && \
-    addgroup -S vpn && \
-    rm -rf /tmp/*
+    apk --no-cache --no-progress add curl unzip iptables ip6tables jq openvpn && \
+	# Download ovpn files
+	curl https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -o /tmp/ovpn.zip && \
+    unzip -q /tmp/ovpn.zip -d /tmp/ovpn && \
+    mkdir -p /vpn/ovpn/ && \
+    mv /tmp/ovpn/*/*.ovpn /vpn/ovpn/ && \
+	# Cleanup
+	rm -rf /tmp/*
 RUN ["cross-build-end"]
-
-COPY openvpn.sh /usr/bin/
-
-HEALTHCHECK --interval=60s --timeout=15s --start-period=120s \
-             CMD curl -L 'https://api.ipify.org'
-
-VOLUME ["/vpn"]
-
-ENTRYPOINT ["openvpn.sh"]
